user nobody nogroup;

worker_processes auto;

events {
    worker_connections 512;
}

http {
    client_max_body_size 250M;
    include mime.types;

    gzip on;
    gzip_http_version 1.1;
    gzip_vary on;
    gzip_comp_level 6;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/javascript text/xml application/xml application/rss+xml application/atom+xml application/rdf+xml image/svg+xml;
    gzip_buffers 16 8k;
    gzip_disable "MSIE [1-6].(?!.*SV1)";

    server {
        listen 80;
        server_name "localhost";

        location / {
            add_header X-Frame-Options DENY;
            add_header X-Content-Type-Options nosniff;
            add_header X-XSS-Protection "1; mode=block";
            add_header Referrer-Policy "no-referrer";
            server_tokens off;

            root /usr/share/nginx/html;
            gzip_static on;
            expires 1y;
            add_header Cache-Control public;
            add_header ETag "";
            try_files $uri /index.html;
        }

        location ~ /api/v(1|2) {
            proxy_pass http://${BACKEND_HOSTNAME}:5001;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_connect_timeout 900;
            proxy_send_timeout 900;
            proxy_read_timeout 900;
            send_timeout 900;
        }
    }

    server {
        listen 443 ssl;
        server_name "localhost";

        ssl_certificate     /etc/nginx/fullchain.cert.pem;
        ssl_certificate_key /etc/nginx/privkey.pem;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location / {
            add_header X-Frame-Options DENY;
            add_header X-Content-Type-Options nosniff;
            add_header X-XSS-Protection "1; mode=block";
            add_header Referrer-Policy "no-referrer";
            server_tokens off;

            root /usr/share/nginx/html;
            gzip_static on;
            expires 1y;
            add_header Cache-Control public;
            add_header ETag "";
            try_files $uri /index.html;
        }

        location ~ /api/v(1|2) {
            proxy_pass http://${BACKEND_HOSTNAME}:5001;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_connect_timeout 900;
            proxy_send_timeout 900;
            proxy_read_timeout 900;
            send_timeout 900;
        }
    }
}
